site_name: √çndice STAR

theme:
  name: material
  logo: assets/logo.png

nav:
  - Inicio: index.md
  - Aplicacion: aplicacion.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
