site_name: √çndice STAR

theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Aplicacion: aplicacion.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
