site_name: √çndice STAR
site_url: https://wagasuhum.github.io/prueba_pagina/

theme:
  name: material
  logo: null
  favicon: null

nav:
  - Inicio: index.md
  - Aplicacion: aplicacion.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
